---
# https://pytorch.org/get-started/locally/
name: ds
channels:
  - conda-forge
  - defaults
  - nvidia
  - nvidia/label/cuda-12.1.0
  - pytorch
dependencies:
  - arrow
  - ca-certificates
  - catboost
  - cudnn
  - flask
  - ipykernel
  - ipython
  - ipywidgets
  - jinja2
  - joblib
  - jq
  - keyring
  - lightgbm
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - nodejs
  - numba
  - numpy
  - nvidia/label/cuda-12.1.0::cuda-toolkit
  - optuna
  - packaging
  - pandas
  - phik
  - pillow
  - pip
  - plotly
  - pyarrow
  - python
  - python-dotenv
  - pytorch
  - pytorch-cuda=12.1
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - selenium
  - setuptools
  - sqlite
  - stack_data
  - statsmodels
  - torchaudio
  - torchvision
  - tqdm
  - urllib3
  - vc
  - vs2015_runtime
  - wheel
  - widgetsnbextension
  - yaml
  - ydata-profiling
  - pip:
    - aiohttp
    - apscheduler
    - html5lib
    - jupyterlab
    - lingua-language-detector
    - markdown2
    - openpyxl
    - psycopg2
    - python-docx
    - python-telegram-bot
    - redis
    - sqlalchemy
    - ultralytics
    - xlrd
