name: ds
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - flask
  - ca-certificates
  - catboost
  - lightgbm
  - ipykernel
  - ipython
  - ipywidgets
  - keyring
  - joblib
  - jupyter-dash
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - numba
  - numpy
  - optuna
  - packaging
  - pandas
  - pillow
  - pip
  - plotly
  - arrow
  - pyarrow
  - python-dotenv
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - sqlite
  - selenium
  - setuptools
  - stack_data
  - statsmodels
  - tqdm
  - urllib3
  - vc
  - vs2015_runtime
  - widgetsnbextension
  - yaml
  - ydata-profiling
  - phik
  - cudatoolkit==11.8
  - cudnn
  - jinja2
  - jq
  - wheel
  - pip:
    - xlrd
    - ultralytics
    - openpyxl
    - psycopg2
    - sqlalchemy
    - jupyterlab
    - markdown2
    - aiohttp
    - redis
    - python-docx
    - apscheduler
    - python-telegram-bot
    - lingua-language-detector
# pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
# https://pytorch.org/get-started/locally/
